### ISSUE TITLE
Add support for node-stats telemetry

### ISSUE THREAD

**Issue by ticheng-aws** [opensearch-project/opensearch-benchmark#259]
**Describe the bug**
The issue was encountered when I tried to collect node-level JVM and CPU data with the node-stats telemetry, `node-stats` level data was missing on the report. Also, I got below warning when I run with an AOS `2.3` domain.

`[WARNING] You have enabled the node-stats telemetry device with OpenSearch < 1.1.0. Requests to the
          _nodes/stats OpenSearch endpoint trigger additional refreshes and WILL SKEW results.`

**To Reproduce**
[TEST_SETUP] Running OSB with commands:
`['opensearch-benchmark', 'execute_test', '--workload', 'http_logs', '--pipeline=<PIPELINE>', '--kill-running-processes', '--client-options', 'basic_auth_user:<USER>,basic_auth_password:<PASSWORD>,timeout:60', '--target-hosts', '<TARGET_HOST>', '--test-procedure', '<TEST_PROCEDURE>', '--telemetry=node-stats', "--workload-params=start_time:<123456789>,end_time:<123456789>,test_index:<TEST_INDEX>,expected_hits:10000,warmup_iterations:5,test_iterations:15,request_cache:'false'", '--include-tasks=type:cluster-health,query1', '--enable-assertions']`

**Expected behavior**
Synced with @IanHoang off-line, we might need to make tweaks within OpenSearch Benchmark to make it ingest metrics for all nodes instead of aggregated.

**Logs**
If applicable, add logs to help explain your problem.

**More Context (please complete the following information):**
- Workload(Share link for custom workloads)
- Service: OpenSearch
- Version:`2.3`

**Additional context**

**Comment by gkamat** [comment]
Taking a look.

**Comment by IanHoang** [comment]
@tclin1023 Side note: In the following OSB release, you will not see this warning anymore when running `node-stats` telemetry device. 
```
[WARNING] You have enabled the node-stats telemetry device with OpenSearch < 1.1.0. Requests to the _nodes/stats OpenSearch endpoint trigger additional refreshes and WILL SKEW results.
```
It was solved in #248 PR

**Comment by tclin1023** [comment]
Hi @IanHoang, Thank you for the information provided. We still have the missing node level JVM memory pressure and CPU utilization issue. Do we have any ECD for this?

**Comment by IanHoang** [comment]
We currently do not have an ECD for this as we're focusing on GA release in the next few weeks. When we have a clearer idea of how to go about this, we can provide an ECD. Also, changing this from bug to enhancement tag as this is more in line with feature request.

**Comment by rishabh6788** [comment]
@ticheng-aws OSB does provide below metadata in the generated metric that will help you filter at node level:
```
"node_name": "ip-172-31-139-38.ec2.internal",
 "host_name": "172.31.139.38",
```

Please note the telemetry data is only ingested into an OpenSearch datastore and not in `in-memory` datastore. 

Feel free to reopen if you have any more queries.
